name: Audit Fix

on:
  workflow_dispatch:

jobs:
  audit-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          fetch-depth: 0

      - name: Get current branch name
        id: vars
        run: echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run audit fix force
        run: npm audit fix --force

      - name: Commit and push
        run: |
          git config user.name "Lewis (CI Bot)"
          git config user.email "lewis@example.com"
          git add package-lock.json
          git diff --cached --quiet || git commit -m "chore: npm audit fix --force"
          git push origin ${{ steps.vars.outputs.branch }}
