name: Force Audit Fix

on:
  workflow_dispatch:

jobs:
  audit-fix-force:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run force audit fix
        run: npm audit fix --force

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add package-lock.json
          git commit -m "Force audit fix applied by GitHub Actions"
          git push
